package com.example.twitturin.core.presentation

import androidx.compose.runtime.staticCompositionLocalOf
import com.example.twitturin.core.domain.preferences.AppLanguage

/**
 * App-wide UI strings. One immutable bundle per [AppLanguage]; the active bundle is provided
 * through [LocalStrings] from the app root, so choosing a language in Settings re-translates
 * every screen instantly (no activity restart needed on any platform).
 *
 * Russian and Uzbek texts are ported from the legacy app's `values-ru`/`values-uz` resources
 * where an equivalent key existed; the rest follow the same tone.
 */
data class Strings(
    // Bottom tabs
    val home: String,
    val search: String,
    val notifications: String,
    val messages: String,
    // Drawer / common destinations
    val profile: String,
    val timetable: String,
    val feedback: String,
    val settings: String,
    val followers: String,
    val following: String,
    val lightMode: String,
    val darkMode: String,
    // Common actions
    val cancel: String,
    val save: String,
    val confirm: String,
    val yes: String,
    val no: String,
    val close: String,
    val delete: String,
    val edit: String,
    val report: String,
    val share: String,
    val logOut: String,
    val continueLabel: String,
    val turnOff: String,
    // Feed
    val noTweetsTitle: String,
    val noTweetsSubtitle: String,
    val showMore: String,
    val showLess: String,
    val newPost: String,
    // Search
    val searchPeople: String,
    val findPeopleTitle: String,
    val findPeopleSubtitle: String,
    val noResultsTitle: String,
    val noResultsSubtitle: String,
    val peopleOnTwitturin: String,
    val voiceSearch: String,
    // Notifications
    val caughtUpTitle: String,
    val caughtUpSubtitle: String,
    val viewPatchNotes: String,
    val versionLabel: String,
    val publishedLabel: String,
    val notifPermissionTitle: String,
    val notifPermissionMessage: String,
    val allow: String,
    // Tweet detail
    val post: String,
    val replyPlaceholder: String,
    val send: String,
    val replyAction: String,
    val likeAction: String,
    val likesSuffix: String,
    val noRepliesYet: String,
    val replyingTo: String,
    val editingReply: String,
    val follow: String,
    val unfollow: String,
    val deleteReplyTitle: String,
    val deleteReplyMessage: String,
    val deletePostTitle: String,
    val deletePostMessage: String,
    // Settings
    val appearance: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val chooseLanguage: String,
    val customization: String,
    val accentColour: String,
    val showNavLabels: String,
    val showNavLabelsSub: String,
    val composeButton: String,
    val composeButtonSub: String,
    val awayMode: String,
    val awayOffSub: String,
    val awayActiveSub: String, // e.g. "Auto-delete after 6 months away"
    val awaySheetTitle: String,
    val awaySheetBody: String,
    val months3: String,
    val months6: String,
    val months12: String,
    val more: String,
    val timetableSub: String,
    val sendFeedback: String,
    val sendFeedbackSub: String,
    val about: String,
    val aboutSub: String,
    // Profile
    val editProfile: String,
    val deleteAccount: String,
    val logOutMessage: String,
    val deleteAccountTitle: String,
    val deleteAccountMessage: String,
    val confirmUsernameTitle: String,
    val confirmUsernameMessage: String, // shown above the input; the username itself is appended by the screen
    val usernamePlaceholder: String,
    val couldNotLoadProfile: String,
    val posts: String,
    val replies: String,
    val likes: String,
    val shareProfile: String,
    // Follow lists
    val noUsersYet: String,
    // Auth
    val signIn: String,
    val signUp: String,
    val username: String,
    val password: String,
    val fullName: String,
    val studentId: String,
    val major: String,
    val subject: String,
    val createAccount: String,
    val studentAccount: String,
    val professorAccount: String,
    val student: String,
    val professor: String,
    val whoAreYou: String,
    val noSpacesAllowed: String,
    // Compose tweet
    val whatsHappening: String,
    val publish: String,
    // Timetable (beta)
    val timetableBetaBadge: String,
    val timetableEmptyTitle: String,
    val timetableUploadCta: String,
    val timetableUploadHint: String,
    val timetableReplace: String,
    val timetableClear: String,
    val timetableClearConfirmMessage: String,
    val timetableRangeDay: String,
    val timetableRangeThreeDay: String,
    val timetableRangeWeek: String,
    val timetableRangeMonth: String,
    val timetableMonthLockedHint: String,
    val timetableSubjectsCta: String,
    val timetableNoSubjectsTitle: String,
    val timetableNoSubjectsSubtitle: String,
    val timetablePickSubjects: String,
    val timetablePickYourGroup: String,
    val timetableSearchSubjects: String,
    val timetableParseErrorRetry: String,
    val timetableToday: String,
    val timetableTimeLabel: String,
    val timetableTeacherLabel: String,
    val timetableRoomLabel: String,
)

val EnglishStrings = Strings(
    home = "Home",
    search = "Search",
    notifications = "Notifications",
    messages = "Messages",
    profile = "Profile",
    timetable = "Timetable",
    feedback = "Feedback",
    settings = "Settings",
    followers = "Followers",
    following = "Following",
    lightMode = "Light mode",
    darkMode = "Dark mode",
    cancel = "Cancel",
    save = "Save",
    confirm = "Confirm",
    yes = "Yes",
    no = "No",
    close = "Close",
    delete = "Delete",
    edit = "Edit",
    report = "Report",
    share = "Share",
    logOut = "Log out",
    continueLabel = "Continue",
    turnOff = "Turn off",
    noTweetsTitle = "No tweets yet",
    noTweetsSubtitle = "Posts from people you follow show up here.",
    showMore = "Show more",
    showLess = "Show less",
    newPost = "New post",
    searchPeople = "Search people",
    findPeopleTitle = "Find people on TwitturIn",
    findPeopleSubtitle = "Search by name or @username.",
    noResultsTitle = "No results found",
    noResultsSubtitle = "Try a different name or username.",
    peopleOnTwitturin = "People on TwitturIn",
    voiceSearch = "Voice search",
    caughtUpTitle = "You're all caught up",
    caughtUpSubtitle = "New notifications will show up here.",
    viewPatchNotes = "View patch notes",
    versionLabel = "Version",
    publishedLabel = "Published",
    notifPermissionTitle = "Enable notifications",
    notifPermissionMessage = "Allow TwitturIn to send you notifications so you never miss what's new.",
    allow = "Allow",
    post = "Post",
    replyPlaceholder = "Reply",
    send = "Send",
    replyAction = "Reply",
    likeAction = "Like",
    likesSuffix = "likes",
    noRepliesYet = "No replies yet — be the first.",
    replyingTo = "Replying to",
    editingReply = "Editing reply",
    follow = "Follow",
    unfollow = "Unfollow",
    deleteReplyTitle = "Delete reply",
    deleteReplyMessage = "This reply and its sub-replies will be removed.",
    deletePostTitle = "Delete post",
    deletePostMessage = "Note that all activity on this post — replies and likes — is deleted with it.",
    appearance = "Appearance",
    theme = "Theme",
    themeSystem = "System default",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    chooseLanguage = "Choose language",
    customization = "Customization",
    accentColour = "Accent colour",
    showNavLabels = "Show navigation labels",
    showNavLabelsSub = "Captions under the bottom bar icons",
    composeButton = "Show compose button",
    composeButtonSub = "Expanded floating button on the feed",
    awayMode = "Away mode",
    awayOffSub = "Off",
    awayActiveSub = "Account deleted after %1 away",
    awaySheetTitle = "If away",
    awaySheetBody = "This feature is needed if you are away: for the chosen amount of time your account will be permanently deleted.",
    months3 = "3 months",
    months6 = "6 months",
    months12 = "12 months",
    more = "More",
    timetableSub = "Open class schedule",
    sendFeedback = "Send feedback",
    sendFeedbackSub = "Report a bug or idea",
    about = "TwitturIn",
    aboutSub = "Version 2.0 · A Twitter-style campus app",
    editProfile = "Edit profile",
    deleteAccount = "Delete account",
    logOutMessage = "Are you sure you want to log out?",
    deleteAccountTitle = "Delete account",
    deleteAccountMessage = "Note that once the account is deleted it cannot be restored, and all activity will be removed.",
    confirmUsernameTitle = "Confirm deletion",
    confirmUsernameMessage = "Type your username to confirm:",
    usernamePlaceholder = "Username",
    couldNotLoadProfile = "Could not load this profile",
    posts = "Posts",
    replies = "Replies",
    likes = "Likes",
    shareProfile = "Share profile",
    noUsersYet = "Nobody here yet",
    signIn = "Sign in",
    signUp = "Sign up",
    username = "Username",
    password = "Password",
    fullName = "Full name",
    studentId = "Student ID",
    major = "Major",
    subject = "Subject",
    createAccount = "Create account",
    studentAccount = "Student account",
    professorAccount = "Professor account",
    student = "Student",
    professor = "Professor",
    whoAreYou = "What is your kind?",
    noSpacesAllowed = "No spaces allowed",
    whatsHappening = "What's happening?",
    publish = "Publish",
    timetableBetaBadge = "Beta",
    timetableEmptyTitle = "No timetable yet",
    timetableUploadCta = "Upload timetable",
    timetableUploadHint = "Import your class schedule as the XML file exported from your school's timetable system.",
    timetableReplace = "Replace timetable",
    timetableClear = "Clear timetable",
    timetableClearConfirmMessage = "This removes the imported timetable and your followed subjects from this device.",
    timetableRangeDay = "Day",
    timetableRangeThreeDay = "3 Days",
    timetableRangeWeek = "Week",
    timetableRangeMonth = "Month",
    timetableMonthLockedHint = "Upload a full-term export to unlock Month view.",
    timetableSubjectsCta = "Followed subjects",
    timetableNoSubjectsTitle = "Pick your subjects",
    timetableNoSubjectsSubtitle = "Choose which classes to show from the subjects found in your upload.",
    timetablePickSubjects = "Pick subjects",
    timetablePickYourGroup = "Pick your group (optional)",
    timetableSearchSubjects = "Search subjects",
    timetableParseErrorRetry = "Try again",
    timetableToday = "Today",
    timetableTimeLabel = "Time",
    timetableTeacherLabel = "Teacher",
    timetableRoomLabel = "Room",
)

val RussianStrings = Strings(
    home = "Главная",
    search = "Поиск",
    notifications = "Уведомления",
    messages = "Сообщения",
    profile = "Профиль",
    timetable = "Расписание",
    feedback = "Обратная связь",
    settings = "Настройки",
    followers = "Подписчики",
    following = "Подписки",
    lightMode = "Светлая тема",
    darkMode = "Тёмная тема",
    cancel = "Отмена",
    save = "Сохранить",
    confirm = "Подтвердить",
    yes = "Да",
    no = "Нет",
    close = "Закрыть",
    delete = "Удалить",
    edit = "Изменить",
    report = "Пожаловаться",
    share = "Поделиться",
    logOut = "Выйти",
    continueLabel = "Продолжить",
    turnOff = "Отключить",
    noTweetsTitle = "Твитов пока нет",
    noTweetsSubtitle = "Здесь появятся публикации людей, на которых вы подписаны.",
    showMore = "Показать ещё",
    showLess = "Свернуть",
    newPost = "Новый пост",
    searchPeople = "Поиск людей",
    findPeopleTitle = "Найдите людей в TwitturIn",
    findPeopleSubtitle = "Ищите по имени или @имени пользователя.",
    noResultsTitle = "Ничего не найдено",
    noResultsSubtitle = "Попробуйте другое имя или имя пользователя.",
    peopleOnTwitturin = "Люди в TwitturIn",
    voiceSearch = "Голосовой поиск",
    caughtUpTitle = "Вы всё просмотрели",
    caughtUpSubtitle = "Новые уведомления появятся здесь.",
    viewPatchNotes = "Список изменений",
    versionLabel = "Версия",
    publishedLabel = "Опубликовано",
    notifPermissionTitle = "Включить уведомления",
    notifPermissionMessage = "Разрешите TwitturIn отправлять уведомления, чтобы ничего не пропустить.",
    allow = "Разрешить",
    post = "Публикация",
    replyPlaceholder = "Ответить…",
    send = "Отправить",
    replyAction = "Ответить",
    likeAction = "Нравится",
    likesSuffix = "лайков",
    noRepliesYet = "Ответов пока нет — будьте первым.",
    replyingTo = "Ответ для",
    editingReply = "Редактирование ответа",
    follow = "Подписаться",
    unfollow = "Отписаться",
    deleteReplyTitle = "Удалить ответ",
    deleteReplyMessage = "Этот ответ и все вложенные ответы будут удалены.",
    deletePostTitle = "Удалить публикацию?",
    deletePostMessage = "Обратите внимание: все действия в публикации — ответы и лайки — тоже будут удалены!",
    appearance = "Оформление",
    theme = "Тема",
    themeSystem = "Как в системе",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    language = "Язык",
    chooseLanguage = "Выберите язык",
    customization = "Персонализация",
    accentColour = "Акцентный цвет",
    showNavLabels = "Подписи навигации",
    showNavLabelsSub = "Подписи под иконками нижней панели",
    composeButton = "Кнопка создания поста",
    composeButtonSub = "Расширенная плавающая кнопка в ленте",
    awayMode = "Режим отсутствия",
    awayOffSub = "Выключен",
    awayActiveSub = "Аккаунт будет удалён после %1 отсутствия",
    awaySheetTitle = "Если вы отсутствуете",
    awaySheetBody = "Эта функция нужна, если вы отсутствуете: по истечении выбранного срока ваш аккаунт будет безвозвратно удалён.",
    months3 = "3 месяца",
    months6 = "6 месяцев",
    months12 = "12 месяцев",
    more = "Ещё",
    timetableSub = "Открыть расписание занятий",
    sendFeedback = "Обратная связь",
    sendFeedbackSub = "Сообщить об ошибке или идее",
    about = "TwitturIn",
    aboutSub = "Версия 2.0 · Кампусное приложение в стиле Twitter",
    editProfile = "Редактировать профиль",
    deleteAccount = "Удалить аккаунт",
    logOutMessage = "Вы действительно хотите выйти?",
    deleteAccountTitle = "Вы уверены, что хотите удалить аккаунт?",
    deleteAccountMessage = "Обратите внимание, что после удаления учётной записи её невозможно восстановить, и вся активность будет удалена.",
    confirmUsernameTitle = "Подтвердите удаление",
    confirmUsernameMessage = "Введите имя пользователя для подтверждения:",
    usernamePlaceholder = "Имя пользователя",
    couldNotLoadProfile = "Не удалось загрузить профиль",
    posts = "Посты",
    replies = "Ответы",
    likes = "Нравится",
    shareProfile = "Поделиться профилем",
    noUsersYet = "Здесь пока никого нет",
    signIn = "Войти",
    signUp = "Зарегистрироваться",
    username = "Имя пользователя",
    password = "Пароль",
    fullName = "Полное имя",
    studentId = "Студент ИД",
    major = "Направление",
    subject = "Предмет",
    createAccount = "Создать аккаунт",
    studentAccount = "Аккаунт студента",
    professorAccount = "Аккаунт профессора",
    student = "Студент",
    professor = "Профессор",
    whoAreYou = "Какой ваш тип?",
    noSpacesAllowed = "Пробелы не допускаются",
    whatsHappening = "Что происходит?",
    publish = "Публиковать",
    timetableBetaBadge = "Бета",
    timetableEmptyTitle = "Расписание не загружено",
    timetableUploadCta = "Загрузить расписание",
    timetableUploadHint = "Импортируйте расписание занятий — XML-файл, экспортированный из системы расписания вашего учебного заведения.",
    timetableReplace = "Заменить расписание",
    timetableClear = "Очистить расписание",
    timetableClearConfirmMessage = "Загруженное расписание и выбранные предметы будут удалены с этого устройства.",
    timetableRangeDay = "День",
    timetableRangeThreeDay = "3 дня",
    timetableRangeWeek = "Неделя",
    timetableRangeMonth = "Месяц",
    timetableMonthLockedHint = "Загрузите расписание на весь семестр, чтобы открыть просмотр по месяцам.",
    timetableSubjectsCta = "Отслеживаемые предметы",
    timetableNoSubjectsTitle = "Выберите предметы",
    timetableNoSubjectsSubtitle = "Выберите, какие занятия показывать, из предметов, найденных в вашем файле.",
    timetablePickSubjects = "Выбрать предметы",
    timetablePickYourGroup = "Выберите вашу группу (необязательно)",
    timetableSearchSubjects = "Поиск предметов",
    timetableParseErrorRetry = "Повторить",
    timetableToday = "Сегодня",
    timetableTimeLabel = "Время",
    timetableTeacherLabel = "Преподаватель",
    timetableRoomLabel = "Аудитория",
)

val UzbekStrings = Strings(
    home = "Asosiy",
    search = "Qidiruv",
    notifications = "Bildirishnomalar",
    messages = "Xabarlar",
    profile = "Profil",
    timetable = "Jadval",
    feedback = "Fikr-mulohaza",
    settings = "Sozlamalar",
    followers = "Obunachilar",
    following = "Kuzatilmoqda",
    lightMode = "Yorugʻ rejim",
    darkMode = "Tungi rejim",
    cancel = "Bekor qilish",
    save = "Saqlash",
    confirm = "Tasdiqlash",
    yes = "Ha",
    no = "Yoʻq",
    close = "Yopish",
    delete = "Oʻchirish",
    edit = "Tahrirlash",
    report = "Shikoyat qilish",
    share = "Ulashish",
    logOut = "Chiqish",
    continueLabel = "Davom etish",
    turnOff = "Oʻchirib qoʻyish",
    noTweetsTitle = "Hozircha tvitlar yoʻq",
    noTweetsSubtitle = "Siz kuzatayotganlarning postlari shu yerda koʻrinadi.",
    showMore = "Koʻproq koʻrsatish",
    showLess = "Kamroq koʻrsatish",
    newPost = "Yangi post",
    searchPeople = "Odamlarni qidirish",
    findPeopleTitle = "TwitturIn'da odamlarni toping",
    findPeopleSubtitle = "Ism yoki @foydalanuvchi nomi boʻyicha qidiring.",
    noResultsTitle = "Hech narsa topilmadi",
    noResultsSubtitle = "Boshqa ism yoki foydalanuvchi nomini sinab koʻring.",
    peopleOnTwitturin = "TwitturIn'dagi odamlar",
    voiceSearch = "Ovozli qidiruv",
    caughtUpTitle = "Hammasini koʻrib chiqdingiz",
    caughtUpSubtitle = "Yangi bildirishnomalar shu yerda paydo boʻladi.",
    viewPatchNotes = "Yangilanishlar roʻyxati",
    versionLabel = "Versiya",
    publishedLabel = "Eʼlon qilingan",
    notifPermissionTitle = "Bildirishnomalarni yoqish",
    notifPermissionMessage = "Yangiliklarni oʻtkazib yubormaslik uchun TwitturIn'ga bildirishnoma yuborishga ruxsat bering.",
    allow = "Ruxsat berish",
    post = "Post",
    replyPlaceholder = "Javob qoldiring…",
    send = "Yuborish",
    replyAction = "Javob berish",
    likeAction = "Yoqdi",
    likesSuffix = "ta yoqtirish",
    noRepliesYet = "Hozircha javoblar yoʻq — birinchi boʻling.",
    replyingTo = "Javob:",
    editingReply = "Javob tahrirlanmoqda",
    follow = "Kuzatish",
    unfollow = "Kuzatishni bekor qilish",
    deleteReplyTitle = "Javobni oʻchirish",
    deleteReplyMessage = "Bu javob va uning ichki javoblari oʻchiriladi.",
    deletePostTitle = "Postni oʻchirasizmi?",
    deletePostMessage = "Eʼtibor bering: postdagi barcha javoblar va yoqtirishlar ham oʻchiriladi!",
    appearance = "Koʻrinish",
    theme = "Mavzu",
    themeSystem = "Tizim boʻyicha",
    themeLight = "Yorugʻ",
    themeDark = "Tungi",
    language = "Til",
    chooseLanguage = "Tilni tanlang",
    customization = "Moslashtirish",
    accentColour = "Urgʻu rangi",
    showNavLabels = "Navigatsiya yozuvlari",
    showNavLabelsSub = "Pastki panel ikonkalari ostidagi yozuvlar",
    composeButton = "Post yozish tugmasi",
    composeButtonSub = "Lentadagi kengaytirilgan suzuvchi tugma",
    awayMode = "Uzoqda rejimi",
    awayOffSub = "Oʻchirilgan",
    awayActiveSub = "%1 uzoqda boʻlsangiz, hisob oʻchiriladi",
    awaySheetTitle = "Agar uzoqda boʻlsangiz",
    awaySheetBody = "Bu funksiya uzoqda boʻlganingizda kerak: tanlangan muddat davomida hisobingiz butunlay oʻchirib tashlanadi.",
    months3 = "3 oy",
    months6 = "6 oy",
    months12 = "12 oy",
    more = "Yana",
    timetableSub = "Dars jadvalini ochish",
    sendFeedback = "Fikr yuborish",
    sendFeedbackSub = "Xato yoki gʻoya haqida xabar bering",
    about = "TwitturIn",
    aboutSub = "Versiya 2.0 · Twitter uslubidagi kampus ilovasi",
    editProfile = "Profilni tahrirlash",
    deleteAccount = "Hisobni oʻchirish",
    logOutMessage = "Haqiqatan ham tizimdan chiqmoqchimisiz?",
    deleteAccountTitle = "Haqiqatan ham hisobni oʻchirib tashlamoqchimisiz?",
    deleteAccountMessage = "Eʼtibor bering, hisob oʻchirilgandan soʻng uni qayta tiklab boʻlmaydi va barcha faollik oʻchiriladi.",
    confirmUsernameTitle = "Oʻchirishni tasdiqlang",
    confirmUsernameMessage = "Tasdiqlash uchun foydalanuvchi nomingizni kiriting:",
    usernamePlaceholder = "Foydalanuvchi nomi",
    couldNotLoadProfile = "Profilni yuklab boʻlmadi",
    posts = "Postlar",
    replies = "Javoblar",
    likes = "Yoqtirishlar",
    shareProfile = "Profilni ulashish",
    noUsersYet = "Bu yerda hali hech kim yoʻq",
    signIn = "Kirish",
    signUp = "Roʻyxatdan oʻtish",
    username = "Foydalanuvchi nomi",
    password = "Parol",
    fullName = "Toʻliq ism",
    studentId = "Student ID",
    major = "Yoʻnalish",
    subject = "Fan",
    createAccount = "Hisob yaratish",
    studentAccount = "Talaba hisobi",
    professorAccount = "Professor hisobi",
    student = "Talaba",
    professor = "Professor",
    whoAreYou = "Siz kimsiz?",
    noSpacesAllowed = "Probel ishlatish mumkin emas",
    whatsHappening = "Nima gaplar?",
    publish = "Eʼlon qilish",
    timetableBetaBadge = "Beta",
    timetableEmptyTitle = "Jadval hali yuklanmagan",
    timetableUploadCta = "Jadvalni yuklash",
    timetableUploadHint = "Dars jadvalingizni maktabingiz jadval tizimidan eksport qilingan XML fayl sifatida import qiling.",
    timetableReplace = "Jadvalni almashtirish",
    timetableClear = "Jadvalni tozalash",
    timetableClearConfirmMessage = "Bu yuklangan jadval va tanlangan fanlaringizni ushbu qurilmadan oʻchiradi.",
    timetableRangeDay = "Kun",
    timetableRangeThreeDay = "3 kun",
    timetableRangeWeek = "Hafta",
    timetableRangeMonth = "Oy",
    timetableMonthLockedHint = "Oylik koʻrinishni ochish uchun butun semestrlik jadvalni yuklang.",
    timetableSubjectsCta = "Kuzatilayotgan fanlar",
    timetableNoSubjectsTitle = "Fanlaringizni tanlang",
    timetableNoSubjectsSubtitle = "Yuklangan faylda topilgan fanlardan qaysilarini koʻrsatishni tanlang.",
    timetablePickSubjects = "Fanlarni tanlash",
    timetablePickYourGroup = "Guruhingizni tanlang (ixtiyoriy)",
    timetableSearchSubjects = "Fanlarni qidirish",
    timetableParseErrorRetry = "Qayta urinish",
    timetableToday = "Bugun",
    timetableTimeLabel = "Vaqt",
    timetableTeacherLabel = "Oʻqituvchi",
    timetableRoomLabel = "Xona",
)

/** Resolves the string bundle for a chosen app language. */
fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.ENGLISH -> EnglishStrings
    AppLanguage.RUSSIAN -> RussianStrings
    AppLanguage.UZBEK -> UzbekStrings
}

/** Ambient string bundle. Provided at the app root from [com.example.twitturin.core.domain.preferences.AppPreferences.language]. */
val LocalStrings = staticCompositionLocalOf { EnglishStrings }
